version: '3'
name: 'kafka_from_csv'

services:
  kafka_from_csv:
    image: kafka_from_csv:deve_kafka
    hostname: kafka_client
    container_name: kafka_from_csv
    environment:
      topic_name: 'my_topic'
      time_interval: '5'
      brokers: 'localhost:9092'
      data_path: 'path_to_csv'
  